# Generated by Django 4.0 on 2023-06-03 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_coordinador_fecha_alta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservadeservicio',
            name='precio',
        ),
    ]
