# Generated by Django 4.1.7 on 2023-06-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_remove_reservadeservicio_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contratacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('proyecto_idea', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='empleado',
            name='numero_legajo',
            field=models.IntegerField(unique=True),
        ),
    ]
